apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z4msa5odx-python
  janus-idp.io/tekton: z4msa5odx-python
  backstage.io/kubernetes-id: z4msa5odx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z4msa5odx-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
